* 绪论
根据 2020 年我国的电力能源结构及电力行业碳排放占比，以燃煤为主的火电在我国电源构成中占比超过一半，电能的生产绝大部分依靠燃煤发电，且在短期内依然会占据较大的份额。随着高比例可再生能源的利用，燃煤电站锅炉需要在宽负荷下灵活运行，以满足电网深度调峰的要求，这对火力发电机组高效率、低污染排放的运营目标带来了极大挑战。当燃煤锅炉运行中出现燃烧不稳定情况时，不仅会降低能源利用效率，增加污染物排放量，还可能造成热分布不均匀、炉壁热应力增大等问题。因此，有必要对锅炉燃烧状态进行有效监测，以确保锅炉安全稳定运行。

火焰稳定性是一个宽泛的概念，主要与燃料的点火稳定性、空气-燃料比、火焰速率和空气-煤粉混合物的速率平衡以及热量释放、声学振荡之间的热声稳定性有关[4-5]。国内外不少学者对火焰稳定性进行了深入的研究。使用各种检测诊断方法，如平面激光诱导荧光图像[6]，红外吸收[7]和摄像机图像[8,9]等。在理论和实验上都进行了大量的研究，以探索火焰不稳定性的机理和特征。同时，还进行了大量的实验来研究火焰稳定性极限[10]和火焰稳定性图表[11-13]，这些研究的结果通常对应于特定的燃料和燃烧器，并给出了可控制参数的范围。Shimoda[35]通过定性分析指出，燃烧火焰的特征辐射波长应该在 6000~7000 埃范围内。Huang[37]介绍了一种用于在线连续闪烁测量燃烧火焰的新型仪表系统。韩义等[20]就燃煤机组最小边界出力条件下的燃烧稳定性做了相应的研究与分析，并建立了稳定性评价方法。Wang[59]提出了一种新的基于深度学习的方法来识别炉膛燃烧状态和测量放热率。

大量专家学者在研究锅炉炉膛燃烧稳定性表征的定量方法和定性方法中，针对不同情况提供了不同的解决方法。然而，由于实际炉膛的燃烧状态受诸多因素的影响，运行工况复杂，很难得出一个统一的方法，对于燃烧系统状态的准确监测仍然处在一个实验探究的阶段。

针对以上问题，本文提出了一种基于层次聚类的火检稳定性判别卷积神经网络模型。首先，在 ABB 火检分析单元的应用基础上，使用采集得到的火检中间值，采用不同的聚类方法，得到燃烧状态分类，结合给煤量的变化情况，建立合适的聚类方法用于确定燃烧状态值；然后，使用短时傅里叶变换得到火检中间值的时频图，并建立起了火焰稳定性判别的卷积神经网络（CNN）模型；最后，对给定了状态标签的时频图进行学习，最后验证了该网络对测试数据集的识别情况，取得了较高的准确率。

* 火检稳定性判别模型原理
种基于时频分析的火检稳定性判别卷积神经网络模型，原理如图 1 所示，具体包括以下三个阶段：

阶段1：（数据采集和预处理）
阶段2：（层次聚类）
阶段3：（卷积神经网络）
 
** 聚类方法
1. 聚类
   聚类是无监督学习的一种，它的概念是将相似的对象归到同一个类中，使得属于同一个类内的数据对象之间相似性尽可能大，同时保证不在同类中的数据对象之间差异性也尽可能地大。对于现场火检数据来说，在对燃烧状态变化过程不完全了解的情况下，要实现通过某种方法将状态尚不明确的样本进行不同状态的划分，就需要从获得的实际火焰检测数据归纳出一个合适的分类依据。


K-Means

DBSCAN(具有噪声的基于密度的聚类方法)

BIRCH(利用层次方法的平衡迭代规约和聚类)

HCA(层次聚类)
   
2. 层次聚类（HCA）
